### ISSUE TITLE
Make home page attractive

### ISSUE THREAD

**Issue by Jittojoyes98** [Jittojoyes98/Dropform#3]
It will be great to make the home page is attractive for users.

**Comment by venkataraviraja5** [comment]
can you assign me i will give my best

**Comment by Jittojoyes98** [comment]
Yeah go ahead. Make sure that you push the code to develop branch. I will review it. I will add the contribution guidelines and all. Stay around  and learn though.

**Comment by Jittojoyes98** [comment]
Any updates @venkataraviraja5  ?
